### ISSUE TITLE
Abiity to handle default for array of type string

### ISSUE THREAD

**Issue by braghettos** [banshee86vr/helm-schema#14]
I would like to use a jsdoc comment to generate the following json schema:

```yaml
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "favoriteColors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": ["blue", "green", "red"]
    }
  }
}
```
